/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import java.util.Scanner

fun main() {
    val f1 = Fraccion(1,2)
    val f2 = Fraccion(1,4)
    println(Fraccion.desdeDecimal(2.3))
    f1.mostrar()
    println(f2.toString())
    println(f2 + f1)
    println(f2 - f1)
    println(f2 * f1)
    println(f2/f1)
    println("Comparaciones")
    println("f1>f2: ${f1>f2}")
    println("f1<f2: ${f1<f2}")
    println("f1>=f2: ${f1>=f2}")
    println("f1<=f2: ${f1<=f2}")
    println("f1==f2: ${f1==f2}")
    println(f1.esMayor(f2))
    println(f1.esMenor(f2))
    println(f1.aDecimal())
    
    val scanner = Scanner(System.`in`)
    val calduladoraFracciones = CalduladoraFracciones()
    var opcion: Int = 10
    
    do {
        calduladoraFracciones.mostrarMenu()
        opcion = scanner.nextInt()  // Leer la opción del menú
        scanner.nextLine()

        when (opcion) {
            1 -> calduladoraFracciones.realizarSuma(scanner)
            2 -> calduladoraFracciones.realizarResta(scanner)
            3 -> calduladoraFracciones.realizarMultiplicacion(scanner)
            4 -> calduladoraFracciones.realizarDivision(scanner)
            5 -> calduladoraFracciones.realizarComparacion(scanner)
            6 -> calduladoraFracciones.convertirADecimal(scanner)
            7 -> calduladoraFracciones.crearDesdeDecimal(scanner)
            8 -> calduladoraFracciones.mostrarEjemplos()
            0 -> println("¡Hasta luego!")
            else -> println("Opción inválida. Intente de nuevo.")
        }
        
        if (opcion != 0) {
            println("\nPresione Enter para continuar...")
            scanner.nextLine() // Limpiar buffer
            scanner.nextLine() // Esperar Enter
        }
    } while (opcion != 0)
    
    scanner.close()
}