/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

fun main() {
    val f1 = Fraccion(1,2)
    val f2 = Fraccion(1,4)
    f2.mostrar()
    println(f1.toString())
    println(f2 + f1)
    println(f2 - f1)
    println(f2 * f1)
    println(f2/f1)
}
